version: "3.9"
services:
  react-frontend:
    image: docdevan/pinpoint:frontend
    container_name: react-frontend
    stdin_open: true
    ports:
      - "80:80"
    networks:
      - point-net
    depends_on:
      - express-backend

  express-backend:
    image: docdevan/pinpoint:backend
    container_name: express-backend
    ports:
      - "5000:5000"
    networks:
      - point-net
    environment:
      - REDIS_URL=redis://redis-stack:6379
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - point-net

networks:
  point-net:
    driver: bridge