name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Create .env file
        run: |
          echo "VITE_MAPBOX_TOKEN=${{ secrets.VITE_MAPBOX_TOKEN }}" >> .env
          echo "VITE_MAPBOX_STYLE=${{ vars.VITE_MAPBOX_STYLE }}" >> .env
          echo "VITE_MAPBOX_STYLE2=${{ vars.VITE_MAPBOX_STYLE2 }}" >> .env
        
      - name: Build and push Docker image for client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: docdevan/pinpoint:frontend

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DB_CONNECTION_URL=${{ secrets.DB_CONNECTION_URL }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
          
      - name: Build and push Docker image for server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: docdevan/pinpoint:backend

  update-latest:
    needs: [build-client, build-server]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build single docker image
        run: docker build -t docdevan/pinpoint:latest .

      - name: Publish image to docker hub
        run: docker push docdevan/pinpoint:latest

  deploy:
    needs: [update-latest]
    runs-on: self-hosted

    steps:
      - name: Pull image from Docker Hub
        run: docker pull docdevan/pinpoint:latest

      - name: Stop and remove all containers
        run: |
          docker stop $(docker ps -a -q) || true
          docker rm $(docker ps -a -q) || true

      - name: Run Docker container
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock docdevan/pinpoint:latest

