name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env file
        run: |
          echo "VITE_MAPBOX_TOKEN=${{ secrets.VITE_MAPBOX_TOKEN }}" >> .env
          echo "VITE_MAPBOX_STYLE=${{ vars.VITE_MAPBOX_STYLE }}" >> .env
          echo "VITE_MAPBOX_STYLE2=${{ vars.VITE_MAPBOX_STYLE2 }}" >> .env

      - name: Build and push Docker image for client
        run: |
          docker build -t docdevan/pinpoint:frontend ./client
          docker push docdevan/pinpoint:frontend

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DB_CONNECTION_URL=${{ secrets.DB_CONNECTION_URL }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env

      - name: Build and push Docker image for server
        run: |
          docker build -t docdevan/pinpoint:backend ./server
          docker push docdevan/pinpoint:backend

  deploy:
    needs: [build-client, build-server]
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull images from Docker Hub
        run: |
          docker pull docdevan/pinpoint:frontend
          docker pull docdevan/pinpoint:backend

      - name: Deploy application using Docker Compose
        run: docker-compose up -d --build



